### PR TITLE
Update stylelint to 7.8.0

### PR DESCRIPTION
**Pull request by patrick91**

### CODE REVIEW

**Comment by shinnn** [comment]
Read https://nodesource.com/blog/semver-tilde-and-caret/ and you'll know this change is totally useless.

**Comment by patrick91** [comment]
Oh, sorry I didn't notice that :)

**Comment by shinnn** [comment]
In vscode-stylelint, I use `npm shrinkwrap` to pin the version of `stylelint` module. The latest version actually uses stylelint v7.8.0. https://github.com/shinnn/vscode-stylelint/commit/be340a90dfc8c518cbe9a7f31c8b22ec4422912e#diff-36018a6a9e1de1798516799b84841318R962

**Comment by patrick91** [comment]
That could have been the issue, right now I just made an hack to use my local version, but I'd like to have support for #3 

If I get some time I'll try to work on it :)

**Comment by shinnn** [comment]
No thanks. Just closed #3.

**Pull request closed without merging**
